### ISSUE TITLE
missing javax.xml.bind.DatatypeConverter on Java 11

### ISSUE THREAD

**Issue by genmeblog** [joinr/vegafx#2]
Java 11 requires more stuff unfortunately.  `javax.xml.bind.DatatypeConverter` is removed in JDK11

See: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by joinr** [comment]
I'll get a java 11 set up.  Good news is I think this is surmountable, related to b64 decoding.  Prolly a portable way to do it.  I'll look after UFC 244 is over, unless pull requests pop first.  Thanks

**Comment by joinr** [comment]
Migrated to java.util.Base64 (added in java 8, should be in java 11).  Haven't tested yet on Java11.  No additional dependencies should be needed.

**Comment by genmeblog** [comment]
Works for me pretty well. Thanks!
